# Generated by Django 5.0.12 on 2025-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebook_stock_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('pre_order', 'Pre-Order')], default='available', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='format_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('ebook', 'E-Book'), ('both', 'Both')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='physical_stock_status',
            field=models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-Order'), ('backorder', 'Backorder'), ('out_of_print', 'Out of Print'), ('print_on_demand', 'Print on Demand')], default='in_stock', max_length=50, null=True),
        ),
    ]
