# Generated by Django 5.0.12 on 2025-08-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_ebook_stock_status_product_format_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebook_file_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='File size in MB', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('zh', 'Chinese'), ('jp', 'Japanese')], default='en', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.PositiveIntegerField(default=120),
            preserve_default=False,
        ),
    ]
