# Generated by Django 5.0.12 on 2025-08-15 16:30

import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_ebook_file_size_product_file_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Enter discount as percentage (e.g., 10 for 10 percent discount)', max_digits=15, validators=[catalog.validators.validate_non_negative])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('notify_customers', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_discounts', to='catalog.product')),
            ],
        ),
    ]
